// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zinhxjgcjgmzzczqgrvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inppbmh4amdjamdtenpjenFncnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjkxNTgsImV4cCI6MjA3MzA0NTE1OH0.VwHAvvwUWKde9FVY5ftuOX1xXRlftLEAqtHLvoB-OgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});